; 模块设置
[interface]
wifi_ssid=ChinaNet-7du8;REGO_Printer2;Printer3;REGO_Printer
wifi_key=8mwhnrkh;rego12345678;rego12345678;rego12345678
wifi_dhcp=1
wifi_ip=192.168.0.100
wifi_mask=255.255.255.0
wifi_gateway=192.168.0.1
eth_mac=82:93:62:AF:FC:C8
eth_dhcp=0
eth_ip=192.168.0.233
eth_mask=255.255.255.0
eth_gateway=192.168.0.1
dns1=208.67.222.222
dns2=8.8.8.8

[tcpcloud]
url=printsrv.quickticket.cn
port=7000
printid=P80B_TEST

[mqtt]
url=a1OWfXsoCSx.iot-as-mqtt.cn-shanghai.aliyuncs.com
port=1883
devicename=RGTEST002&a1OWfXsoCSx
deviceid=a1OWfXsoCSx.RGTEST002|securemode=2,signmethod=hmacsha256,timestamp=1669109433892|
password=87b7f3b9a017bffaa869a77dfaf15a5897b26c4201e4a2b3d5534b8797a17c9f
topic_sub=/a1OWfXsoCSx/RGTEST002/user/data
topic_pub=/a1OWfXsoCSx/RGTEST002/user/status
ping=180
serverurl=http://36.154.212.123:30080/cloud-print/v1/devices/server-info
serverprintsn=411000000000001

[iot]
aliyun_deviceName=RGTEST001
aliyun_productKey=a1OWfXsoCSx
aliyun_deviceSecret=d8d527a1c205a4fecdc71df48af64f87
aliyun_topic=/a1OWfXsoCSx/RGTEST001/user/data

[version]
data=C01,C02,C03,C04,C05,C10,C12,C20
[http]
url=192.168.0.100
path=/printer
id=111
port=8899
polling=10
